// <auto-generated />
using System;
using Aranya.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aranya.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260414151136_updateTblVilla")]
    partial class updateTblVilla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.6.23329.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aranya.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsActive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tbl_Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = "5000 sq ft",
                            CreatedDate = new DateTime(2026, 4, 14, 20, 41, 35, 813, DateTimeKind.Local).AddTicks(3636),
                            Description = "This is the description of the Royal Villa",
                            ImageUrl = "",
                            IsActive = "Y",
                            Name = "Royal Villa For Family",
                            Occupancy = 4,
                            Rate = 200.0,
                            UpdatedDate = new DateTime(2026, 4, 14, 20, 41, 35, 813, DateTimeKind.Local).AddTicks(3651)
                        },
                        new
                        {
                            Id = 2,
                            Area = "5000 sq ft",
                            CreatedDate = new DateTime(2026, 4, 14, 20, 41, 35, 813, DateTimeKind.Local).AddTicks(3657),
                            Description = "A special room for a special memories.",
                            ImageUrl = "",
                            IsActive = "Y",
                            Name = "Honeymoon sweet For Couple",
                            Occupancy = 4,
                            Rate = 200.0,
                            UpdatedDate = new DateTime(2026, 4, 14, 20, 41, 35, 813, DateTimeKind.Local).AddTicks(3658)
                        },
                        new
                        {
                            Id = 3,
                            Area = "5000 sq ft",
                            CreatedDate = new DateTime(2026, 4, 14, 20, 41, 35, 813, DateTimeKind.Local).AddTicks(3662),
                            Description = "This is the delux ville with AC.",
                            ImageUrl = "",
                            IsActive = "Y",
                            Name = "Delux villa for couple",
                            Occupancy = 4,
                            Rate = 200.0,
                            UpdatedDate = new DateTime(2026, 4, 14, 20, 41, 35, 813, DateTimeKind.Local).AddTicks(3663)
                        },
                        new
                        {
                            Id = 4,
                            Area = "5000 sq ft",
                            CreatedDate = new DateTime(2026, 4, 14, 20, 41, 35, 813, DateTimeKind.Local).AddTicks(3667),
                            Description = "This is the description of the Sea facing Villa",
                            ImageUrl = "",
                            IsActive = "Y",
                            Name = "Sea facing villa",
                            Occupancy = 4,
                            Rate = 200.0,
                            UpdatedDate = new DateTime(2026, 4, 14, 20, 41, 35, 813, DateTimeKind.Local).AddTicks(3668)
                        },
                        new
                        {
                            Id = 5,
                            Area = "5000 sq ft",
                            CreatedDate = new DateTime(2026, 4, 14, 20, 41, 35, 813, DateTimeKind.Local).AddTicks(3672),
                            Description = "This is the description of the Tree Villa with AC and 2 rooms.",
                            ImageUrl = "",
                            IsActive = "Y",
                            Name = "Tree Villa",
                            Occupancy = 4,
                            Rate = 200.0,
                            UpdatedDate = new DateTime(2026, 4, 14, 20, 41, 35, 813, DateTimeKind.Local).AddTicks(3673)
                        });
                });

            modelBuilder.Entity("Aranya.Domain.Entities.VillaNumber", b =>
                {
                    b.Property<int>("Villa_Number")
                        .HasColumnType("int");

                    b.Property<string>("SpecialDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VillaID")
                        .HasColumnType("int");

                    b.HasKey("Villa_Number");

                    b.HasIndex("VillaID");

                    b.ToTable("Tbl_VillaNumber");

                    b.HasData(
                        new
                        {
                            Villa_Number = 103,
                            VillaID = 1
                        },
                        new
                        {
                            Villa_Number = 104,
                            VillaID = 2
                        },
                        new
                        {
                            Villa_Number = 105,
                            VillaID = 2
                        },
                        new
                        {
                            Villa_Number = 108,
                            VillaID = 1
                        },
                        new
                        {
                            Villa_Number = 203,
                            VillaID = 1
                        });
                });

            modelBuilder.Entity("Aranya.Domain.Entities.VillaNumber", b =>
                {
                    b.HasOne("Aranya.Domain.Entities.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
