// <auto-generated />
using System;
using Aranya.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aranya.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.6.23329.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aranya.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tbl_Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = "5000 sq ft",
                            CreatedDate = new DateTime(2026, 4, 8, 23, 43, 19, 223, DateTimeKind.Local).AddTicks(9057),
                            Description = "This is the description of the Royal Villa",
                            ImageUrl = "",
                            Name = "Royal Villa For Family",
                            Occupancy = 4,
                            Rate = 200.0,
                            UpdatedDate = new DateTime(2026, 4, 8, 23, 43, 19, 223, DateTimeKind.Local).AddTicks(9072)
                        },
                        new
                        {
                            Id = 2,
                            Area = "5000 sq ft",
                            CreatedDate = new DateTime(2026, 4, 8, 23, 43, 19, 223, DateTimeKind.Local).AddTicks(9079),
                            Description = "A special room for a special memories.",
                            ImageUrl = "",
                            Name = "Honeymoon sweet For Couple",
                            Occupancy = 4,
                            Rate = 200.0,
                            UpdatedDate = new DateTime(2026, 4, 8, 23, 43, 19, 223, DateTimeKind.Local).AddTicks(9084)
                        },
                        new
                        {
                            Id = 3,
                            Area = "5000 sq ft",
                            CreatedDate = new DateTime(2026, 4, 8, 23, 43, 19, 223, DateTimeKind.Local).AddTicks(9088),
                            Description = "This is the delux ville with AC.",
                            ImageUrl = "",
                            Name = "Delux villa for couple",
                            Occupancy = 4,
                            Rate = 200.0,
                            UpdatedDate = new DateTime(2026, 4, 8, 23, 43, 19, 223, DateTimeKind.Local).AddTicks(9089)
                        },
                        new
                        {
                            Id = 4,
                            Area = "5000 sq ft",
                            CreatedDate = new DateTime(2026, 4, 8, 23, 43, 19, 223, DateTimeKind.Local).AddTicks(9093),
                            Description = "This is the description of the Sea facing Villa",
                            ImageUrl = "",
                            Name = "Sea facing villa",
                            Occupancy = 4,
                            Rate = 200.0,
                            UpdatedDate = new DateTime(2026, 4, 8, 23, 43, 19, 223, DateTimeKind.Local).AddTicks(9095)
                        },
                        new
                        {
                            Id = 5,
                            Area = "5000 sq ft",
                            CreatedDate = new DateTime(2026, 4, 8, 23, 43, 19, 223, DateTimeKind.Local).AddTicks(9099),
                            Description = "This is the description of the Tree Villa with AC and 2 rooms.",
                            ImageUrl = "",
                            Name = "Tree Villa",
                            Occupancy = 4,
                            Rate = 200.0,
                            UpdatedDate = new DateTime(2026, 4, 8, 23, 43, 19, 223, DateTimeKind.Local).AddTicks(9101)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
